language: node_js

sudo: false
dist: trusty

sudo: required
services:
  - docker

script:
  - docker build --tag patients-manager-api backend
  - docker build --tag patients-manager-web frontend

after_script:
  - docker images
