language: node_js
node_js:
  - "13.14"

dist: trusty

sudo: required
services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker
    - $HOME/.npm

before_script:
  - npm install -g @angular/cli

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - BUILD_DATE=$(date --iso-8601=seconds)
  - VERSION=$(echo $TRAVIS_BRANCH | sed 's/\//-/g')
  - sed -i "s/{VERSION_HOLDER}/$VERSION/g" frontend/src/environments/environment.prod.ts
  - sed -i "s/{BUILD_DATE_HOLDER}/$BUILD_DATE/g" frontend/src/environments/environment.prod.ts
  - sed -i "s/{VERSION_HOLDER}/$VERSION/g" backend/version.json
  - sed -i "s/{BUILD_DATE_HOLDER}/$BUILD_DATE/g" backend/version.json
  - cat backend/version.json

script:
  - npm ci --prefix backend || travis_terminate 1;
  - npm run build --prefix backend || travis_terminate 1;
  - ls -lrth backend || travis_terminate 1;
  - npm ci --prefix frontend || travis_terminate 1;
  - npm run build:prod --prefix frontend || travis_terminate 1;
  - docker build --tag patients-manager-api -f backend/Dockerfile-ci backend || travis_terminate 1;
  - docker build --tag patients-manager-web -f frontend/Dockerfile-ci frontend || travis_terminate 1;
  - ls -lrth $HOME/.npm

after_script:
  - DOCKER_TAG=$(echo $TRAVIS_BRANCH | sed 's/\//-/g')
  - if [[ $TRAVIS_BRANCH == "master" ]]; then DOCKER_TAG="latest"; fi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker tag patients-manager-api $DOCKER_USERNAME/patients-manager-api:$DOCKER_TAG || travis_terminate 1;
  - docker tag patients-manager-web $DOCKER_USERNAME/patients-manager-web:$DOCKER_TAG || travis_terminate 1;
  - docker push $DOCKER_USERNAME/patients-manager-api:$DOCKER_TAG || travis_terminate 1;
  - docker push $DOCKER_USERNAME/patients-manager-web:$DOCKER_TAG || travis_terminate 1;