language: node_js

sudo: false
dist: trusty

sudo: required
services:
  - docker

script:
  - docker build --tag patients-manager-api --cache-from $DOCKER_USERNAME/patients-manager-api:latest backend
  - docker build --tag patients-manager-web --cache-from $DOCKER_USERNAME/patients-manager-web:latest frontend

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker tag patients-manager-api $DOCKER_USERNAME/patients-manager-api
  - docker tag patients-manager-web $DOCKER_USERNAME/patients-manager-web
  - docker push $DOCKER_USERNAME/patients-manager-api
  - docker push $DOCKER_USERNAME/patients-manager-web
