language: node_js
node_js:
  - "10.11"

sudo: false
dist: trusty

sudo: required
services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker
    - $HOME/.npm

before_script:
  - npm install -g @angular/cli

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - npm ci --prefix backend
  - npm run build --prefix backend
  - npm ci --prefix frontend
  - npm run build:prod --prefix frontend
  - docker build --tag patients-manager-api:latest backend
  - docker build --tag patients-manager-web:latest frontend
  - ls -lrth $HOME/.npm

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker tag patients-manager-api $DOCKER_USERNAME/patients-manager-api
  - docker tag patients-manager-web $DOCKER_USERNAME/patients-manager-web
  - docker push $DOCKER_USERNAME/patients-manager-api
  - docker push $DOCKER_USERNAME/patients-manager-web