version: "3"

services:
  traefik:
    image: "traefik:v1.7"
    restart: always
    command: -c /treafik.toml
    volumes:
      - "${PWD}/traefik.toml:/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  #######################################
  # Patients manager
  #######################################
  patients-manager-web:
    image: "akraxx/patients-manager-web:latest"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=PathPrefix:/"
  patients-manager-api:
    image: "akraxx/patients-manager-api:latest"
    environment:
      MONGO_HOST: mongodb
    labels:
    - "traefik.port=4000"
    - "traefik.frontend.rule=PathPrefix:/api"
  mongodb:
    ports:
