version: "3"

services:
  #######################################
  # Patients manager
  #######################################
  patients-manager-web:
    build:
      context: frontend
    volumes:
    - "${PWD}/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    labels:
    - "traefik.docker.network=reverse-proxy"
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.rule=PathPrefix:/"
  patients-manager-api:
    build:
      context: backend
    links:
      - mongodb
    environment:
      MONGO_HOST: mongodb
    labels:
    - "traefik.docker.network=reverse-proxy"
    - "traefik.enable=true"
    - "traefik.port=4000"
    - "traefik.frontend.rule=PathPrefix:/api"
